# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "5.5.5-security-enhanced" ]
  pull_request:
    branches: [ "5.5.5-security-enhanced" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'
    - name: Build with Ant
      run: |
        ant --noconfig -noinput -Djavac.source=1.8 -Djavac.target=1.8 -Dversion.java=1.8 -Divy.settings.file=ivy-settings.xml -buildfile build.xml ivy-bootstrap
        ant -lib /home/runner/.ant/lib -Djavac.source=1.8 -Djavac.target=1.8 -Dversion.java=1.8 -Divy.settings.file=ivy-settings.xml -buildfile build.xml compile jar
